runner:
  name: linear_prob
  val_interval: 2
  val_interval_steps: -1

epoch: 90

dist:
  name: torch
  fp16: True #for torch dist 
  param:
    opt_level: O1 # for apex dist 

log:
  interval_train: 10
  interval_val: 1

wandb:
  enable: False
  project: project_name
  entity: entity_name

ckpt:
  dir: ./output
  step_interval: 2000
  filename: step_checkpoint.pth
  external_resume: ./ckpts/simseg.vit-b.pth
  only_load_image_encoder: True

# Optimizing configurations
optim:
  name: LARS
  param:
    lr: 0.001 # no use, for avoding intialization bug
    momentum: 0.9
    weight_decay: 0.0

  lr:
    name: cosine_schedule_with_warmup
    init: 6.4 # lr is set here
    warmup_proportion: 0.1111
    param:
      num_cycles: 0.5


# ----- DATASET BUILDER -----
data:
  exp_name: imagenet.linear_prob.simseg_pretrained
  name: imagenet_local
  train_steps: -1

  data_path: ./data/ILSVRC/Data/CLS-LOC/ # directory of your dataset

  batch_size: 16384
  batch_size_val: 16384

  num_workers: 2
  enable_valid: True
  single_eval: False
  cuda_eval: True

# ----- TRAMSFORM BUILDER -----
transforms:
  train_transforms:  [random_resize_crop, autoaug]
  valid_transforms: [resize, center_crop]

  resize:
    size: 256
  center_crop:
    size: 224
  random_resize_crop:
    size: 224
    scale: [0.08, 1.0]
  input_size: 224 # declare for vit
  normalize:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

# ----- MODEL BUILDER -----
model:
  name: linear_prob

  image_encoder:
    name: timm_modelzoo
    tag: vit_base_patch16_224_in21k
    embedding_dim: 768
    pretrained: False
    trainable: False
    vit:
      only_cls_token: True

  pool:
    name: identity

  classifier:
    num_classes: 1000

  syncbn: True
  interpolate_pos_embed: False

# ----- LOSS BUILDER -----
loss:
  name: CrossEntropy
